name: Build and Release Monokit UI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      version: ${{ steps.release-please.outputs.version }}
      body: ${{ steps.release-please.outputs.body }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: node
          package-name: monokit-ui

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun --bun i
      - name: Build project
        run: bun --bun run build
      - name: Prepare assets for embedding
        run: bun --bun run prepare-assets
      - name: Compile executable
        run: bun --bun build --compile --minify --sourcemap index.ts embedded-imports.js --outfile build/monokit-ui
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: monokit-ui-build
          path: build/monokit-ui

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun --bun i
      - name: Run tests
        run: bun --bun test

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [build, test, release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun --bun i
      - name: Build project
        run: bun --bun run build
      - name: Prepare assets for embedding
        run: bun --bun run prepare-assets
      - name: Compile executable
        run: bun --bun build --compile --minify --sourcemap index.ts embedded-imports.js --outfile build/monokit-ui
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          name: Release ${{ needs.release-please.outputs.tag_name }}
          body: ${{ needs.release-please.outputs.body }}
          files: |
            build/monokit-ui
          draft: false
          prerelease: false
